# Generated by Django 3.1 on 2020-08-09 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='veg_or_nonveg',
            field=models.CharField(choices=[('N', 'NonVeg'), ('V', 'Veg')], default='N', max_length=20),
            preserve_default=False,
        ),
    ]
