# Generated by Django 3.1 on 2020-08-09 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_auto_20200809_1834'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='quanity',
            field=models.CharField(choices=[('250gm', '250gm'), ('500gm', '500gm'), ('1kg', '1kg')], default='250gm', max_length=20),
            preserve_default=False,
        ),
    ]
