# Generated by Django 3.1 on 2020-08-09 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0005_auto_20200809_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='quantity',
            field=models.CharField(choices=[('250gm', '250gm'), ('500gm', '500gm'), ('1kg', '1kg'), ('1', '1'), ('2', '2'), ('3', '3')], max_length=20),
        ),
    ]
