# Generated by Django 3.1 on 2020-08-10 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0011_item_discount_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='cartitem',
            field=models.IntegerField(default=1),
        ),
    ]
