# Generated by Django 3.1 on 2020-08-10 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0012_item_cartitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='cartitem',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='cartitem',
            field=models.IntegerField(default=1),
        ),
    ]
