# Generated by Django 3.1 on 2020-08-14 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0023_auto_20200814_0933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, default='dish_images/default.jpg', null=True, upload_to='dish_images'),
        ),
    ]
