# Generated by Django 3.1 on 2020-08-14 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0024_auto_20200814_0934'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='image',
        ),
    ]
