# Generated by Django 3.1 on 2020-09-02 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0030_refund'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='shipping_address',
        ),
    ]
