# Generated by Django 3.1 on 2020-09-03 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0031_remove_order_shipping_address'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='billingaddress',
            options={'verbose_name_plural': 'Addresses'},
        ),
        migrations.RenameField(
            model_name='order',
            old_name='being_delivered',
            new_name='delivered',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='received',
            new_name='on_the_way',
        ),
        migrations.AddField(
            model_name='order',
            name='order_accepted',
            field=models.BooleanField(default=False),
        ),
    ]
