# Generated by Django 3.1 on 2020-09-03 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0032_auto_20200903_1101'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_cancelled',
            field=models.BooleanField(default=False),
        ),
    ]
