# Generated by Django 3.1 on 2020-09-03 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0034_order_refund_completed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='payment',
            new_name='payment_id',
        ),
    ]
