# Generated by Django 3.1 on 2020-09-03 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0036_auto_20200903_1116'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='applied_coupon',
            new_name='coupon',
        ),
    ]
