# Generated by Django 3.1 on 2020-09-03 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0037_auto_20200903_1304'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='payment_id',
            new_name='payment',
        ),
    ]
