# Generated by Django 3.1 on 2020-09-03 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0038_auto_20200903_1340'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='delivered',
        ),
        migrations.RemoveField(
            model_name='order',
            name='on_the_way',
        ),
        migrations.RemoveField(
            model_name='order',
            name='order_accepted',
        ),
        migrations.RemoveField(
            model_name='order',
            name='order_cancelled',
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('order_accepted', 'order_accepted'), ('order_cancelled', 'order_cancelled'), ('on_the_way', 'on_the_way'), ('delivered', 'delivered')], default='order_accepted', max_length=50),
            preserve_default=False,
        ),
    ]
