# Generated by Django 3.1 on 2020-09-03 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0040_auto_20200903_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='timestamp',
            field=models.DateTimeField(),
        ),
    ]
