# Generated by Django 3.1 on 2020-09-03 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0041_auto_20200903_1933'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='timestamp',
        ),
    ]
