# Generated by Django 3.1 on 2020-09-04 04:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0042_remove_orderitem_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='expire_in',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coupon',
            name='min_order_value',
            field=models.FloatField(default=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('not_accepted', 'not_accepted'), ('order_accepted', 'order_accepted'), ('order_cancelled', 'order_cancelled'), ('on_the_way', 'on_the_way'), ('delivered', 'delivered')], default='not_accepted', max_length=50),
        ),
    ]
