# Generated by Django 3.1 on 2020-09-04 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0043_auto_20200904_0947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='min_order_value',
            field=models.FloatField(blank=True, default=10, null=True),
        ),
    ]
