# Generated by Django 3.1 on 2020-09-04 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0044_auto_20200904_0948'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingaddress',
            name='contact_no',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
