# Generated by Django 3.1 on 2020-09-04 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0045_billingaddress_contact_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingaddress',
            name='contact_no',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
