# Generated by Django 3.1 on 2020-09-06 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0046_auto_20200904_1152'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=50)),
                ('query', models.TextField()),
                ('mobile_no', models.IntegerField()),
                ('timestamp', models.DateField()),
            ],
        ),
    ]
