# Generated by Django 3.1 on 2020-09-06 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0047_contactus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactus',
            name='timestamp',
        ),
    ]
