# Generated by Django 3.1 on 2020-09-06 11:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0048_remove_contactus_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='timestamp',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
