# Generated by Django 3.1 on 2020-09-07 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0051_auto_20200907_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paytmpayment',
            name='checksum_hash',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
