# Generated by Django 3.1 on 2020-09-07 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0052_auto_20200907_1110'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='paytm_payment_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='paytmpayment',
            name='checksum_hash',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
