# Generated by Django 3.1 on 2020-09-07 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0054_auto_20200907_1719'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='checksum_hash',
        ),
    ]
